@extends('layouts.app')
@section('title',$advertiser->exists?'Editar anunciante':'Novo anunciante')
@section('content')
<section class="content-band"><p class="eyebrow">Comercial</p><h1>{{ $advertiser->exists?'Editar anunciante':'Novo anunciante' }}</h1></section>
<section class="settings-panel"><form class="admin-form" method="post" action="{{ $advertiser->exists?route('admin.advertisers.update',$advertiser):route('admin.advertisers.store') }}">@csrf @if($advertiser->exists) @method('PUT') @endif
<label>Razão social<input name="legal_name" required value="{{ old('legal_name',$advertiser->legal_name) }}"></label><label>Nome fantasia<input name="trade_name" value="{{ old('trade_name',$advertiser->trade_name) }}"></label><label>CNPJ/CPF<input name="document_number" value="{{ old('document_number',$advertiser->document_number) }}"></label><label>Inscrição estadual<input name="state_registration" value="{{ old('state_registration',$advertiser->state_registration) }}"></label><label>Inscrição municipal<input name="municipal_registration" value="{{ old('municipal_registration',$advertiser->municipal_registration) }}"></label><label>Segmento<input name="segment" value="{{ old('segment',$advertiser->segment) }}"></label>
<label>Porte<select name="company_size"><option value="">Selecione</option>@foreach(['mei'=>'MEI','micro'=>'Microempresa','small'=>'Pequena','medium'=>'Média','large'=>'Grande'] as $k=>$v)<option value="{{ $k }}" @selected(old('company_size',$advertiser->company_size)===$k)>{{ $v }}</option>@endforeach</select></label>
<label>Status<select name="commercial_status" required>@foreach(['prospect'=>'Prospect','contact'=>'Primeiro contato','negotiation'=>'Negociação','proposal'=>'Proposta enviada','contracted'=>'Contrato assinado','active'=>'Cliente ativo','inactive'=>'Inativo','cancelled'=>'Cancelado'] as $k=>$v)<option value="{{ $k }}" @selected(old('commercial_status',$advertiser->commercial_status?:'prospect')===$k)>{{ $v }}</option>@endforeach</select></label>
<label>Responsável<select name="responsible_user_id"><option value="">Não definido</option>@foreach($responsibles as $u)<option value="{{ $u->id }}" @selected(old('responsible_user_id',$advertiser->responsible_user_id)==$u->id)>{{ $u->name }}</option>@endforeach</select></label><label>E-mail<input type="email" name="email" required value="{{ old('email',$advertiser->email?:$advertiser->user?->email) }}"></label><label>Telefone<input name="contact_phone" value="{{ old('contact_phone',$advertiser->contact_phone) }}"></label><label>WhatsApp<input name="whatsapp" value="{{ old('whatsapp',$advertiser->whatsapp) }}"></label><label>Site<input type="url" name="website" value="{{ old('website',$advertiser->website) }}"></label>
<label>Receita contratada<input type="number" step="0.01" min="0" name="contracted_revenue" value="{{ old('contracted_revenue',$advertiser->contracted_revenue?:0) }}"></label><label>Receita prevista<input type="number" step="0.01" min="0" name="expected_revenue" value="{{ old('expected_revenue',$advertiser->expected_revenue?:0) }}"></label><label>Início do contrato<input type="date" name="contract_starts_at" value="{{ old('contract_starts_at',$advertiser->contract_starts_at?->format('Y-m-d')) }}"></label><label>Fim do contrato<input type="date" name="contract_ends_at" value="{{ old('contract_ends_at',$advertiser->contract_ends_at?->format('Y-m-d')) }}"></label><label>Observações<textarea name="notes">{{ old('notes',$advertiser->notes) }}</textarea></label><label><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$advertiser->exists?$advertiser->is_active:true))> Cadastro ativo</label><button class="primary-action">Salvar anunciante</button></form></section>
@endsection
