@extends('layouts.app')
@section('title','Assinantes')
@section('content')
<section class="content-band"><p class="eyebrow">Fase 14.3 · Assinaturas</p><h1>Assinantes</h1><p>Cadastro, plano, status, histórico e cancelamentos.</p></section>
<section class="category-admin-list">@foreach([['Total',$metrics['total']],['Ativos',$metrics['active']],['Vencem em 30 dias',$metrics['expiring']],['Cancelados',$metrics['cancelled']]] as [$label,$value])<article class="settings-panel"><small>{{ $label }}</small><h2>{{ $value }}</h2></article>@endforeach</section>
<section class="settings-panel"><form class="admin-form" method="get"><label>Pesquisar<input name="q" value="{{ request('q') }}" placeholder="Nome ou e-mail"></label><label>Status<select name="status"><option value="">Todos</option>@foreach(['active'=>'Ativo','inactive'=>'Inativo','expired'=>'Expirado','suspended'=>'Suspenso','cancelled'=>'Cancelado'] as $key=>$label)<option value="{{ $key }}" @selected(request('status')===$key)>{{ $label }}</option>@endforeach</select></label><button class="secondary-action">Filtrar</button></form></section>
@forelse($subscriptions as $subscription)<section class="settings-panel"><p class="eyebrow">{{ $subscription->status }} · {{ $subscription->plan?->name??'Sem plano' }}</p><h2>{{ $subscription->user->name }}</h2><p>{{ $subscription->user->email }} · início {{ $subscription->starts_at?->format('d/m/Y')??'—' }} · fim {{ $subscription->ends_at?->format('d/m/Y')??'sem prazo' }}</p><details><summary>Histórico</summary>@forelse($subscription->histories as $history)<p>{{ $history->created_at->format('d/m/Y H:i') }} · {{ $history->event }} · {{ $history->from_status??'—' }} → {{ $history->to_status??'—' }} · {{ $history->fromPlan?->name??'—' }} → {{ $history->toPlan?->name??'—' }}<br>{{ $history->notes }}</p>@empty<p>Sem histórico.</p>@endforelse</details><details><summary>Pagamentos</summary>@forelse($subscription->payments as $payment)<p>{{ $payment->created_at->format('d/m/Y H:i') }} · R$ {{ number_format((float)$payment->amount,2,',','.') }} · {{ $payment->status }}</p>@if($payment->status==='paid' && (float)$payment->refunded_amount<(float)$payment->amount)<form class="admin-form" method="post" action="{{ route('admin.subscription-payments.refund',$payment) }}">@csrf<label>Valor do reembolso<input type="number" name="amount" min=".01" max="{{ (float)$payment->amount-(float)$payment->refunded_amount }}" step=".01" required></label><label>Motivo<textarea name="reason" required minlength="5"></textarea></label><button class="secondary-action">Reembolsar pelo gateway</button></form>@endif @empty<p>Sem pagamentos.</p>@endforelse</details></section>@empty<p>Nenhum assinante.</p>@endforelse
{{ $subscriptions->links() }}
@endsection
