<?php
namespace App\Services;use App\Models\NewsArticle;use App\Models\VideoScript;use Illuminate\Support\Facades\Http;use Illuminate\Support\Str;use Throwable;
class VideoScriptGenerator{
 public function generate(NewsArticle $article,int $duration,?int $userId=null):VideoScript{$duration=max(30,min(600,$duration));$provider='local';$model=null;$data=null;$key=(string)config('luzicity.ai.openai_api_key');if($key!==''){try{$model=(string)config('luzicity.ai.chatgpt_model','gpt-4o-mini');$response=Http::withToken($key)->timeout(60)->post('https://api.openai.com/v1/chat/completions',['model'=>$model,'response_format'=>['type'=>'json_object'],'messages'=>[['role'=>'system','content'=>'Crie roteiro jornalístico em JSON com title, teleprompter_text, editorial_notes e scenes (array de title, narration, visual, duration_seconds). Não invente fatos.'],['role'=>'user','content'=>"Duração alvo: {$duration}s\nTítulo: {$article->title}\nResumo: {$article->excerpt}\nTexto: ".Str::limit(strip_tags($article->body),10000,'')]]]);if($response->successful()){$data=json_decode((string)data_get($response->json(),'choices.0.message.content'),true);if(is_array($data))$provider='openai';}}catch(Throwable){$data=null;}}
  $data=$data?:$this->fallback($article,$duration);$scenes=collect($data['scenes']??[])->map(fn($s)=>['title'=>Str::limit((string)($s['title']??'Cena'),120,''),'narration'=>Str::limit((string)($s['narration']??''),3000,''),'visual'=>Str::limit((string)($s['visual']??''),1000,''),'duration_seconds'=>max(1,(int)($s['duration_seconds']??10))])->values()->all();$teleprompter=Str::limit((string)($data['teleprompter_text']??''),20000,'');$estimated=max(1,(int)ceil(str_word_count($teleprompter)/2.5));
  return VideoScript::create(['news_article_id'=>$article->id,'title'=>Str::limit((string)($data['title']??$article->title),180,''),'status'=>'pending_review','provider'=>$provider,'model'=>$model,'target_duration_seconds'=>$duration,'estimated_duration_seconds'=>$estimated,'scenes'=>$scenes,'teleprompter_text'=>$teleprompter,'editorial_notes'=>$data['editorial_notes']??'Revisar fatos, nomes, números e imagens antes da gravação.','created_by'=>$userId]);
 }
 private function fallback(NewsArticle $a,int $duration):array{$summary=$a->excerpt?:Str::limit(strip_tags($a->body),500);return['title'=>$a->title,'teleprompter_text'=>$a->title.".\n\n".$summary."\n\nConfira a reportagem completa na Luzicity.",'editorial_notes'=>'Roteiro-base local: exige apuração e revisão humana antes da gravação.','scenes'=>[['title'=>'Abertura','narration'=>$a->title,'visual'=>'Apresentador e identificação da pauta.','duration_seconds'=>min(15,$duration)],['title'=>'Contexto','narration'=>$summary,'visual'=>'Imagens de apoio verificadas pela redação.','duration_seconds'=>max(15,$duration-25)],['title'=>'Encerramento','narration'=>'Confira mais informações na Luzicity.','visual'=>'Marca e chamada final.','duration_seconds'=>10]]];}
}
