@extends('layouts.app',['title'=>'Estrutura da Rádio - Luzicity'])
@section('content')
<section class="content-band"><p class="eyebrow">Fase 11.1</p><h1>Estrutura da Rádio</h1><p>Gerencie emissora, locutores, programas, grade e status no ar.</p></section>
<section class="settings-panel"><h2>Emissora</h2><form method="post" action="{{ route('admin.radio-structure.station') }}" class="admin-form">@csrf @method('put')<label>Nome <input name="name" required value="{{ $station?->name ?? 'Rádio Web Luzicity' }}"></label><label>Prefixo <input name="call_sign" value="{{ $station?->call_sign }}"></label><label>Descrição <textarea name="description">{{ $station?->description }}</textarea></label><label>Streaming <input type="url" name="stream_url" value="{{ $station?->stream_url }}"></label><label>Texto no ar <input name="on_air_label" value="{{ $station?->on_air_label }}"></label><label class="inline-check"><input type="checkbox" name="force_on_air" value="1" @checked($station?->force_on_air)> Forçar status no ar</label><button class="secondary-action">Salvar emissora</button></form></section>
<section class="settings-panel"><h2>Novo locutor</h2><form method="post" action="{{ route('admin.radio-structure.host') }}" class="admin-form">@csrf<label>Nome <input name="name" required></label><label>Biografia <textarea name="bio"></textarea></label><button class="secondary-action">Cadastrar locutor</button></form></section>
<section class="settings-panel"><h2>Novo programa</h2><form method="post" action="{{ route('admin.radio-structure.program') }}" class="admin-form">@csrf<label>Nome <input name="name" required></label><label>Locutor <select name="radio_host_id"><option value="">Sem locutor</option>@foreach($hosts as $host)<option value="{{ $host->id }}">{{ $host->name }}</option>@endforeach</select></label><label>Descrição <textarea name="description"></textarea></label><button class="secondary-action">Cadastrar programa</button></form></section>
<section class="settings-panel"><h2>Adicionar à grade</h2><form method="post" action="{{ route('admin.radio-structure.slot') }}" class="admin-form">@csrf<label>Programa <select name="radio_program_id" required>@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->name }}</option>@endforeach</select></label><label>Dia <select name="day_of_week">@foreach(['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'] as $i=>$day)<option value="{{ $i }}">{{ $day }}</option>@endforeach</select></label><label>Início <input type="time" name="starts_at" required></label><label>Fim <input type="time" name="ends_at" required></label><label class="inline-check"><input type="checkbox" name="is_live" value="1" checked> Ao vivo</label><button class="secondary-action">Adicionar horário</button></form></section>
<section class="category-admin-list"><h2>Programas e grade</h2>@foreach($programs as $program)<article class="settings-panel"><h3>{{ $program->name }}</h3><p>{{ $program->host?->name ?: 'Sem locutor' }}</p>@foreach($program->slots as $slot)<small>{{ ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'][$slot->day_of_week] }} {{ substr($slot->starts_at,0,5) }}–{{ substr($slot->ends_at,0,5) }} {{ $slot->is_live?'· ao vivo':'' }}</small><br>@endforeach</article>@endforeach</section>
@endsection
