<?php
namespace App\Http\Controllers;use App\Jobs\RenderVideoClipJob;use App\Models\Video;use App\Models\VideoClip;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\View\View;
class AdminVideoClipController extends Controller{
 public function index():View{$this->guard();return view('admin.video-clips.index',['videos'=>Video::where('provider','file')->latest()->get(),'clips'=>VideoClip::with(['video','requester'])->latest()->paginate(30),'ffmpegConfigured'=>$this->ffmpegConfigured()]);}
 public function store(Request $r):RedirectResponse{$this->guard();$max=(int)config('media.max_clip_seconds',180);$d=$r->validate(['video_id'=>'required|exists:videos,id','title'=>'required|string|max:180','aspect_ratio'=>'required|in:9:16,1:1,16:9','starts_at_seconds'=>'required|numeric|min:0','ends_at_seconds'=>'required|numeric|gt:starts_at_seconds|max:86400','caption_text'=>'nullable|string|max:10000']);abort_if(($d['ends_at_seconds']-$d['starts_at_seconds'])>$max,422,"O recorte deve ter no máximo {$max} segundos.");$clip=VideoClip::create(['video_id'=>$d['video_id'],'title'=>$d['title'],'aspect_ratio'=>$d['aspect_ratio'],'starts_at_ms'=>(int)round($d['starts_at_seconds']*1000),'ends_at_ms'=>(int)round($d['ends_at_seconds']*1000),'caption_text'=>$d['caption_text']??null,'status'=>'queued','requested_by'=>$r->user()->id]);RenderVideoClipJob::dispatch($clip->id);return back()->with('status','Recorte enviado para a fila de renderização.');}
 public function retry(VideoClip $clip):RedirectResponse{$this->guard();$clip->update(['status'=>'queued','error_message'=>null]);RenderVideoClipJob::dispatch($clip->id);return back()->with('status','Renderização reenviada.');}
 public function review(Request $r,VideoClip $clip):RedirectResponse{$this->guard();abort_unless($clip->status==='pending_review',422);$status=$r->validate(['decision'=>'required|in:approved,rejected'])['decision'];$clip->update(['status'=>$status,'reviewed_by'=>$r->user()->id,'reviewed_at'=>now()]);return back()->with('status','Revisão registrada.');}
 private function ffmpegConfigured():bool{$b=(string)config('media.ffmpeg_binary','ffmpeg');return is_file($b)||!empty((new \Symfony\Component\Process\ExecutableFinder)->find($b));}private function guard():void{abort_unless(auth()->user()?->hasAnyRole(['Super Admin','Admin','Jornalista']),403);}
}
