@extends('layouts.app',['title'=>'Central de Rádio e Áudio - Luzicity'])
@section('content')
<section class="content-band"><p class="eyebrow">Consolidação Fase 11</p><h1>Central de Rádio e Áudio</h1><p>Visão operacional da emissora, grade, podcasts, áudio assistido, publicidade e filas.</p></section>
<section class="system-health-stats">@foreach($stats as $label=>$value)<article class="settings-panel system-health-stat"><span>{{ str_replace('_',' ',$label) }}</span><strong>{{ $value }}</strong></article>@endforeach</section>
<section class="settings-panel"><h2>{{ $station?->name ?: 'Emissora ainda não configurada' }}</h2>@if($onAir)<p class="eyebrow">No ar agora</p><h3>{{ $onAir->program->name }}</h3><p>{{ $onAir->program->host?->name }}</p>@else<p>Nenhum programa ao vivo neste horário.</p>@endif
<a class="secondary-action" href="{{ route('admin.radio-structure.index') }}">Emissora e grade</a><a class="secondary-action" href="{{ route('admin.podcasts.index') }}">Podcasts</a><a class="secondary-action" href="{{ route('admin.news-narrations.index') }}">Texto para áudio</a><a class="secondary-action" href="{{ route('admin.audio-ads.index') }}">Publicidade</a><a class="secondary-action" href="{{ route('radio.index') }}" target="_blank">Abrir player público</a></section>
<section class="settings-panel"><h2>Filas e custos</h2><p>Fila de áudio: <strong>{{ $queue['audio'] }}</strong> · fila padrão: <strong>{{ $queue['default'] }}</strong></p><p>Custo acumulado de narrações: <strong>{{ number_format($audioCost,6,',','.') }}</strong></p></section>
<section class="category-admin-list"><h2>Narrações recentes</h2>@forelse($narrations as $item)<article class="settings-panel"><strong>{{ $item->article->title }}</strong><p>{{ $item->status }} · {{ $item->voiceProfile->name }} · {{ number_format($item->actual_cost ?? $item->estimated_cost,6,',','.') }}</p></article>@empty<p>Sem narrações.</p>@endforelse</section>
<section class="category-admin-list"><h2>Campanhas de áudio</h2>@forelse($campaigns as $campaign)<article class="settings-panel"><strong>{{ $campaign->name }}</strong><p>{{ $campaign->status }} · {{ $campaign->plays_count }} reproduções</p></article>@empty<p>Sem campanhas.</p>@endforelse</section>
<section class="category-admin-list"><h2>Podcasts</h2>@forelse($podcasts as $series)<article class="settings-panel"><strong>{{ $series->title }}</strong><p>{{ $series->episodes_count }} episódios · {{ $series->is_published?'publicada':'rascunho' }}</p></article>@empty<p>Sem séries.</p>@endforelse</section>
@endsection
