@extends('layouts.app')
@section('title',$advertiser->trade_name ?: $advertiser->legal_name)
@section('content')
<section class="content-band"><p class="eyebrow">{{ $advertiser->commercial_status }}</p><h1>{{ $advertiser->trade_name ?: $advertiser->legal_name }}</h1><p>{{ $advertiser->legal_name }} · {{ $advertiser->document_number }}</p><a class="secondary-action" href="{{ route('admin.advertisers.edit',$advertiser) }}">Editar cadastro</a></section>
<section class="category-admin-list"><article class="settings-panel"><h2>Resumo comercial</h2><p>Responsável: {{ $advertiser->responsible?->name ?: 'Não definido' }}</p><p>Receita contratada: R$ {{ number_format((float)$advertiser->contracted_revenue,2,',','.') }}</p><p>Receita prevista: R$ {{ number_format((float)$advertiser->expected_revenue,2,',','.') }}</p><p>Contrato: {{ $advertiser->contract_starts_at?->format('d/m/Y') ?: '—' }} até {{ $advertiser->contract_ends_at?->format('d/m/Y') ?: '—' }}</p></article><article class="settings-panel"><h2>Contato principal</h2><p>{{ $advertiser->email }}</p><p>{{ $advertiser->contact_phone }} · {{ $advertiser->whatsapp }}</p><p>{{ $advertiser->website }}</p></article></section>
<section class="settings-panel"><h2>Novo contato</h2><form method="post" action="{{ route('admin.advertisers.contacts.store',$advertiser) }}" class="admin-form">@csrf<label>Nome<input name="name" required></label><label>Cargo<input name="position"></label><label>Telefone<input name="phone"></label><label>WhatsApp<input name="whatsapp"></label><label>E-mail<input type="email" name="email"></label><label><input type="checkbox" name="is_primary" value="1"> Principal</label><button class="secondary-action">Adicionar</button></form>@foreach($advertiser->contacts as $c)<p><strong>{{ $c->name }}</strong> · {{ $c->position }} · {{ $c->phone }} · {{ $c->email }}</p>@endforeach</section>
<section class="settings-panel"><h2>Novo endereço</h2><form method="post" action="{{ route('admin.advertisers.addresses.store',$advertiser) }}" class="admin-form">@csrf<label>Tipo<select name="type"><option value="commercial">Comercial</option><option value="billing">Cobrança</option><option value="mailing">Correspondência</option></select></label><label>CEP<input name="postal_code"></label><label>Logradouro<input name="street"></label><label>Número<input name="number"></label><label>Complemento<input name="complement"></label><label>Bairro<input name="district"></label><label>Cidade<input name="city"></label><label>UF<input name="state" maxlength="2"></label><button class="secondary-action">Adicionar</button></form>@foreach($advertiser->addresses as $a)<p>{{ $a->type }}: {{ $a->street }}, {{ $a->number }} — {{ $a->city }}/{{ $a->state }}</p>@endforeach</section>
<section class="settings-panel"><h2>Documentos</h2><form method="post" enctype="multipart/form-data" action="{{ route('admin.advertisers.documents.store',$advertiser) }}" class="admin-form">@csrf<label>Tipo<select name="type"><option value="contract">Contrato</option><option value="cnpj">Cartão CNPJ</option><option value="logo">Logomarca</option><option value="media">Mídia</option><option value="proposal">Proposta</option><option value="other">Outro</option></select></label><label>Arquivo<input type="file" name="document" required></label><button class="secondary-action">Enviar</button></form>@foreach($advertiser->documents as $d)<p>{{ $d->type }} · {{ $d->name }} · {{ number_format($d->size_bytes/1024,1,',','.') }} KB</p>@endforeach</section>
<section class="settings-panel"><h2>Histórico comercial</h2><form method="post" action="{{ route('admin.advertisers.histories.store',$advertiser) }}" class="admin-form">@csrf<label>Tipo<select name="type"><option value="meeting">Reunião</option><option value="call">Ligação</option><option value="email">E-mail</option><option value="visit">Visita</option><option value="proposal">Proposta</option><option value="note">Observação</option></select></label><label>Título<input name="title" required></label><label>Data<input type="datetime-local" name="occurred_at"></label><label>Descrição<textarea name="description"></textarea></label><button class="secondary-action">Registrar</button></form>@foreach($advertiser->histories as $h)<article><strong>{{ $h->title }}</strong><p>{{ $h->occurred_at?->format('d/m/Y H:i') }} · {{ $h->type }} · {{ $h->user?->name }}</p><p>{{ $h->description }}</p></article>@endforeach</section>
@endsection
