<?php
namespace App\Http\Controllers;use App\Models\PodcastSeries;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Illuminate\View\View;
class AdminPodcastController extends Controller{
 public function index():View{$this->guard();return view('admin.podcasts.index',['seriesList'=>PodcastSeries::with('episodes')->latest()->get()]);}
 public function series(Request $r):RedirectResponse{$this->guard();$d=$r->validate(['title'=>'required|string|max:160','description'=>'nullable|string|max:5000','author'=>'nullable|string|max:120','language'=>'required|string|max:10','cover'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:8192']);$d['slug']=$this->slug($d['title']);$d['is_published']=$r->boolean('is_published');if($r->hasFile('cover'))$d['cover_path']=$r->file('cover')->store('podcasts/covers','public');unset($d['cover']);PodcastSeries::create($d);return back()->with('status','Série criada.');}
 public function episode(Request $r,PodcastSeries $series):RedirectResponse{$this->guard();$d=$r->validate(['title'=>'required|string|max:180','description'=>'nullable|string|max:10000','audio'=>'nullable|file|mimes:mp3,m4a,mp4,wav,ogg|max:102400','audio_url'=>'nullable|url|max:2048','duration_seconds'=>'nullable|integer|min:0','episode_number'=>'nullable|integer|min:1','published_at'=>'nullable|date']);abort_if(!$r->hasFile('audio')&&!filled($d['audio_url']??null),422,'Informe um áudio ou URL.');$d['slug']=$this->slug($d['title'],$series);$d['is_published']=$r->boolean('is_published');$d['published_at']=$d['is_published']?($d['published_at']??now()):null;if($r->hasFile('audio')){$file=$r->file('audio');$d['audio_path']=$file->store('podcasts/audio','public');$d['audio_mime']=$file->getMimeType()?:'audio/mpeg';$d['audio_bytes']=$file->getSize();}else{$d['audio_path']=$d['audio_url'];$d['audio_mime']='audio/mpeg';}unset($d['audio'],$d['audio_url']);$series->episodes()->create($d);return back()->with('status','Episódio salvo.');}
 private function slug(string $title,?PodcastSeries $series=null):string{$base=Str::slug($title)?:'podcast';$slug=$base;$n=2;while(($series?$series->episodes():PodcastSeries::query())->where('slug',$slug)->exists())$slug=$base.'-'.$n++;return $slug;}
 private function guard():void{abort_unless(auth()->user()?->hasAnyRole(['Super Admin','Admin']),403);}
}
