<?php
namespace App\Services;
use App\Models\AgencyApprovalAction;use App\Models\EditorialPitch;use App\Models\RssImportedArticle;use App\Models\RssPrePitch;use App\Models\User;use Illuminate\Database\Eloquent\Model;use Illuminate\Support\Facades\DB;use InvalidArgumentException;
class AgencyApprovalService{
 public function approveArticle(RssImportedArticle $article,User $actor):RssPrePitch{return DB::transaction(function()use($article,$actor){$item=app(RssPrePitchService::class)->generate($article,$actor->id);$this->record($article,'approve_for_pre_pitch',$article->collection_status,'pre_pitch',$actor);$article->update(['collection_status'=>'pre_pitch']);return $item;});}
 public function approvePrePitch(RssPrePitch $item,User $actor):EditorialPitch{return DB::transaction(function()use($item,$actor){if($item->status!=='pending_review')throw new InvalidArgumentException('Pré-pauta já decidida.');$pitch=EditorialPitch::create(['title'=>$item->title,'summary'=>$item->summary."\n\nRelevância local: ".$item->local_relevance."\n\nRecomendação: ".$item->editorial_recommendation,'status'=>'idea','priority'=>'normal','created_by'=>$actor->id]);foreach($item->source_links as $source)$pitch->sources()->create(['title'=>$source['title']??$source['name']??null,'url'=>$source['url']??null,'notes'=>'Fonte originada de pré-pauta RSS.']);foreach($item->questions as $i=>$question)$pitch->tasks()->create(['description'=>$question,'position'=>$i]);$this->record($item,'approve_for_writing',$item->status,'approved_to_editorial',$actor);$item->update(['status'=>'approved_to_editorial']);return $pitch;});}
 public function decide(Model $item,string $action,User $actor,?string $note=null):void{if(!in_array($action,['reject','archive'],true))throw new InvalidArgumentException('Ação inválida.');$field=$item instanceof RssImportedArticle?'collection_status':'status';$from=$item->{$field};$to=$action==='reject'?'rejected':'archived';$item->update([$field=>$to]);$this->record($item,$action,$from,$to,$actor,$note);}
 private function record(Model $item,string $action,?string $from,string $to,User $actor,?string $note=null):void{AgencyApprovalAction::create(['approvable_type'=>$item::class,'approvable_id'=>$item->getKey(),'action'=>$action,'from_status'=>$from,'to_status'=>$to,'note'=>$note,'user_id'=>$actor->id]);}
}
