<?php
namespace App\Http\Controllers;
use App\Models\EditorialPitch;use App\Models\EditorialPitchSource;use App\Models\EditorialSourceClaim;use App\Services\EditorialSourceResearchService;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;
class AdminEditorialSourceController extends Controller{
 public function store(Request $r,EditorialPitch $pitch):RedirectResponse{$d=$r->validate(['title'=>['nullable','string','max:180'],'url'=>['nullable','url','max:2048'],'document'=>['nullable','file','mimes:txt,md,pdf,doc,docx','max:5120'],'reliability'=>['required','in:unrated,low,medium,high']]);abort_if(blank($d['url']??null)&&!$r->hasFile('document'),422,'Informe URL ou documento.');$path=$r->hasFile('document')?$r->file('document')->store('editorial-sources'):null;$pitch->sources()->create(['title'=>$d['title']?:($r->file('document')?->getClientOriginalName()),'url'=>$d['url']??null,'source_type'=>$path?'document':'url','document_path'=>$path,'reliability'=>$d['reliability']]);return back()->with('status','Fonte adicionada.');}
 public function fetch(EditorialPitchSource $source,EditorialSourceResearchService $research):RedirectResponse{abort_unless($source->url,422);$source->update($research->fetch($source->url));return back()->with('status','Metadados e trecho seguro atualizados.');}
 public function claim(Request $r,EditorialPitchSource $source):RedirectResponse{$d=$r->validate(['claim'=>['required','string','max:2000']]);EditorialSourceClaim::create(['editorial_pitch_id'=>$source->editorial_pitch_id,'editorial_pitch_source_id'=>$source->id,'claim'=>$d['claim']]);$this->detect($source->pitch);return back()->with('status','Afirmação relacionada à fonte.');}
 private function detect(EditorialPitch $pitch):void{$claims=EditorialSourceClaim::where('editorial_pitch_id',$pitch->id)->get();foreach($claims as $claim){$words=collect(preg_split('/\s+/u',mb_strtolower($claim->claim)))->filter(fn($w)=>mb_strlen($w)>4);$other=$claims->first(fn($x)=>$x->id!==$claim->id&&$words->intersect(preg_split('/\s+/u',mb_strtolower($x->claim)))->count()>=2&&(str_contains(mb_strtolower($claim->claim),' não ') xor str_contains(mb_strtolower($x->claim),' não ')));if($other)$claim->update(['status'=>'contradicted','contradiction_note'=>"Possível divergência com a afirmação #{$other->id}; exige verificação humana."]);}}
}
