@extends('layouts.app')
@section('title','Planos de assinatura')
@section('content')
<section class="content-band"><p class="eyebrow">Fase 14.1 · Assinaturas</p><h1>Planos</h1><p>Gerencie planos gratuitos, premium, VIP e empresariais.</p><a class="primary-action" target="_blank" href="{{ route('subscription-plans.index') }}">Ver página pública</a></section>
<section class="settings-panel"><h2>Novo plano</h2><form class="admin-form" method="post" action="{{ route('admin.subscription-plans.store') }}">@csrf
<label>Nome<input name="name" required></label><label>Slug<input name="slug"></label><label>Mensal<input type="number" name="monthly_price" min="0" step=".01" required></label><label>Anual<input type="number" name="yearly_price" min="0" step=".01" required></label><label>Ordem<input type="number" name="display_order" min="0" value="0"></label><label>Descrição<textarea name="description"></textarea></label><label>Benefícios (um por linha)<textarea name="benefits_text"></textarea></label><label>Limite mensal de artigos<input type="number" name="monthly_article_limit" min="1"></label><label>Caracteres da prévia<input type="number" name="preview_characters" min="100" max="5000" value="600" required></label><label><input type="checkbox" name="can_access_premium" value="1"> Acessa conteúdo premium</label><label><input type="checkbox" name="is_ad_free" value="1"> Sem anúncios</label><label><input type="checkbox" name="is_featured" value="1"> Destaque</label><label><input type="checkbox" name="is_active" value="1" checked> Ativo</label><button class="primary-action">Criar plano</button></form></section>
@foreach($plans as $plan)<section class="settings-panel"><h2>{{ $plan->name }}</h2><p>{{ $plan->subscriptions_count }} assinaturas · R$ {{ number_format((float)$plan->monthly_price,2,',','.') }}/mês</p><form class="admin-form" method="post" action="{{ route('admin.subscription-plans.update',$plan) }}">@csrf @method('PUT')
<label>Nome<input name="name" value="{{ $plan->name }}" required></label><label>Slug<input name="slug" value="{{ $plan->slug }}"></label><label>Mensal<input type="number" name="monthly_price" min="0" step=".01" value="{{ $plan->monthly_price }}" required></label><label>Anual<input type="number" name="yearly_price" min="0" step=".01" value="{{ $plan->yearly_price }}" required></label><label>Ordem<input type="number" name="display_order" min="0" value="{{ $plan->display_order }}"></label><label>Descrição<textarea name="description">{{ $plan->description }}</textarea></label><label>Benefícios<textarea name="benefits_text">{{ implode("\n",$plan->benefits??[]) }}</textarea></label><label>Limite mensal<input type="number" name="monthly_article_limit" min="1" value="{{ $plan->monthly_article_limit }}"></label><label>Caracteres da prévia<input type="number" name="preview_characters" min="100" max="5000" value="{{ $plan->preview_characters }}" required></label><label><input type="checkbox" name="can_access_premium" value="1" @checked($plan->can_access_premium)> Acessa conteúdo premium</label><label><input type="checkbox" name="is_ad_free" value="1" @checked($plan->is_ad_free)> Sem anúncios</label><label><input type="checkbox" name="is_featured" value="1" @checked($plan->is_featured)> Destaque</label><label><input type="checkbox" name="is_active" value="1" @checked($plan->is_active)> Ativo</label><button class="secondary-action">Atualizar</button></form></section>@endforeach
@endsection
