<?php
namespace App\Http\Controllers;use App\Models\Video;use App\Models\VideoCategory;use App\Models\VideoPlaylist;use App\Models\VideoSeries;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Str;use Illuminate\View\View;
class AdminVideoLibraryController extends Controller{
 public function index():View{$this->guard();return view('admin.videos.index',['categories'=>VideoCategory::orderBy('name')->get(),'seriesList'=>VideoSeries::orderBy('title')->get(),'videos'=>Video::with(['category','series'])->latest()->get(),'playlists'=>VideoPlaylist::with('videos')->get()]);}
 public function category(Request $r):RedirectResponse{$this->guard();$d=$r->validate(['name'=>'required|string|max:100']);VideoCategory::create($d+['slug'=>$this->slug($d['name'],VideoCategory::class)]);return back()->with('status','Categoria criada.');}
 public function series(Request $r):RedirectResponse{$this->guard();$d=$r->validate(['title'=>'required|string|max:160','description'=>'nullable|string|max:5000','video_category_id'=>'nullable|exists:video_categories,id','thumbnail'=>'nullable|image|max:8192']);$d['slug']=$this->slug($d['title'],VideoSeries::class);$d['is_published']=$r->boolean('is_published');if($r->hasFile('thumbnail'))$d['thumbnail_path']=$r->file('thumbnail')->store('videos/thumbnails','public');unset($d['thumbnail']);VideoSeries::create($d);return back()->with('status','Série criada.');}
 public function video(Request $r):RedirectResponse{$this->guard();$d=$r->validate(['title'=>'required|string|max:180','description'=>'nullable|string|max:10000','video_category_id'=>'nullable|exists:video_categories,id','video_series_id'=>'nullable|exists:video_series,id','provider'=>'required|in:file,youtube,vimeo,hls','video'=>'nullable|file|mimes:mp4,webm,mov,m4v|max:512000','video_url'=>'nullable|url|max:2048','thumbnail'=>'nullable|image|max:8192','subtitle'=>'nullable|file|mimes:vtt,txt|max:2048','subtitle_language'=>'required|string|max:10','duration_seconds'=>'nullable|integer|min:0','episode_number'=>'nullable|integer|min:1','published_at'=>'nullable|date']);abort_if(!$r->hasFile('video')&&!filled($d['video_url']??null),422,'Informe o vídeo.');$d['slug']=$this->slug($d['title'],Video::class);$d['is_published']=$r->boolean('is_published');$d['published_at']=$d['is_published']?($d['published_at']??now()):null;$d['video_path']=$r->hasFile('video')?$r->file('video')->store('videos/files','public'):$d['video_url'];if($r->hasFile('thumbnail'))$d['thumbnail_path']=$r->file('thumbnail')->store('videos/thumbnails','public');if($r->hasFile('subtitle'))$d['subtitle_path']=$r->file('subtitle')->store('videos/subtitles','public');unset($d['video'],$d['video_url'],$d['thumbnail'],$d['subtitle']);Video::create($d);return back()->with('status','Vídeo salvo.');}
 public function playlist(Request $r):RedirectResponse{$this->guard();$d=$r->validate(['title'=>'required|string|max:160','description'=>'nullable|string|max:5000','videos'=>'nullable|array','videos.*'=>'exists:videos,id']);$p=VideoPlaylist::create(['title'=>$d['title'],'slug'=>$this->slug($d['title'],VideoPlaylist::class),'description'=>$d['description']??null,'is_published'=>$r->boolean('is_published')]);$p->videos()->sync(collect($d['videos']??[])->mapWithKeys(fn($id,$i)=>[$id=>['position'=>$i]])->all());return back()->with('status','Playlist criada.');}
 private function slug(string $value,string $model):string{$base=Str::slug($value)?:'video';$slug=$base;$i=2;while($model::where('slug',$slug)->exists())$slug=$base.'-'.$i++;return $slug;}private function guard():void{abort_unless(auth()->user()?->hasAnyRole(['Super Admin','Admin']),403);}
}
