<?php
namespace App\Http\Controllers;
use App\Models\Category;use App\Models\EditorialPitch;use App\Models\User;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Validation\Rule;use Illuminate\View\View;
class AdminEditorialPitchController extends Controller{
 public function index(Request $r):View{$q=EditorialPitch::with(['category','assignee','tasks','sources'])->when($r->filled('assignee_id'),fn($q)=>$q->where('assignee_id',$r->integer('assignee_id')))->orderBy('position')->latest();return view('admin.editorial-pitches.index',['columns'=>$q->get()->groupBy('status'),'statuses'=>EditorialPitch::STATUSES,'users'=>User::active()->orderBy('name')->get()]);}
 public function create():View{return $this->form(new EditorialPitch(['status'=>'idea','priority'=>'normal']));}
 public function store(Request $r):RedirectResponse{$pitch=EditorialPitch::create($this->data($r)+['created_by'=>$r->user()->id]);$this->sync($pitch,$r);return redirect()->route('admin.editorial-pitches.edit',$pitch)->with('status','Pauta criada.');}
 public function edit(EditorialPitch $pitch):View{$pitch->load(['sources','tasks','comments.user']);return $this->form($pitch);}
 public function update(Request $r,EditorialPitch $pitch):RedirectResponse{$pitch->update($this->data($r));$this->sync($pitch,$r);return back()->with('status','Pauta atualizada.');}
 public function move(Request $r,EditorialPitch $pitch):RedirectResponse{$v=$r->validate(['status'=>['required',Rule::in(array_keys(EditorialPitch::STATUSES))],'position'=>['nullable','integer','min:0']]);$pitch->update($v);return back()->with('status','Pauta movimentada.');}
 private function form(EditorialPitch $pitch):View{return view('admin.editorial-pitches.form',compact('pitch')+['statuses'=>EditorialPitch::STATUSES,'categories'=>Category::orderBy('name')->get(),'users'=>User::active()->orderBy('name')->get()]);}
 private function data(Request $r):array{return $r->validate(['title'=>['required','string','max:180'],'summary'=>['nullable','string','max:5000'],'status'=>['required',Rule::in(array_keys(EditorialPitch::STATUSES))],'priority'=>['required','in:low,normal,high,urgent'],'category_id'=>['nullable','exists:categories,id'],'assignee_id'=>['nullable','exists:users,id'],'news_article_id'=>['nullable','exists:news_articles,id'],'due_at'=>['nullable','date']]);}
 private function sync(EditorialPitch $p,Request $r):void{$p->sources()->delete();foreach(array_filter($r->input('sources',[]),fn($x)=>filled($x['url']??null)||filled($x['title']??null)) as $s)$p->sources()->create(['title'=>$s['title']??null,'url'=>$s['url']??null,'notes'=>$s['notes']??null]);$p->tasks()->delete();foreach(array_filter($r->input('tasks',[]),fn($x)=>filled($x['description']??null)) as $i=>$t)$p->tasks()->create(['description'=>$t['description'],'is_completed'=>isset($t['is_completed']),'position'=>$i]);if(filled($r->input('comment')))$p->comments()->create(['user_id'=>$r->user()->id,'body'=>$r->validate(['comment'=>'string|max:3000'])['comment']]);}
}
