@extends('layouts.app',['title'=>'Central TV Web - Luzicity'])
@section('content')
<section class="content-band"><p class="eyebrow">Consolidação Fase 12</p><h1>Central TV Web</h1><p>Player, programação, vídeos, roteiros, recortes e integrações em uma única visão.</p></section>
<section class="system-health-stats">@foreach($stats as $label=>$value)<article class="settings-panel system-health-stat"><span>{{ str_replace('_',' ',$label) }}</span><strong>{{ $value }}</strong></article>@endforeach</section>
<section class="settings-panel"><a class="secondary-action" href="{{ route('admin.tv.index') }}">Canais e transmissões</a><a class="secondary-action" href="{{ route('admin.videos.index') }}">Videoteca</a><a class="secondary-action" href="{{ route('admin.video-scripts.index') }}">Roteiros IA</a><a class="secondary-action" href="{{ route('admin.video-clips.index') }}">Shorts e Reels</a><a class="secondary-action" href="{{ route('tv.index') }}" target="_blank">Abrir TV pública</a><a class="secondary-action" href="{{ route('videos.index') }}" target="_blank">Abrir videoteca</a></section>
<section class="settings-panel"><h2>Renderização</h2><p>FFmpeg: <strong>{{ $ffmpegConfigured?'disponível':'não configurado' }}</strong> · fila: <strong>{{ $renderQueue }}</strong></p>@unless($ffmpegConfigured)<p>Defina <code>FFMPEG_BINARY</code> no .env para habilitar a renderização dos recortes.</p>@endunless</section>
<section class="category-admin-list"><h2>Ao vivo</h2>@forelse($live as $item)<article class="settings-panel"><p class="eyebrow">{{ $item->provider }}</p><h3>{{ $item->title }}</h3><p>{{ $item->channel->name }}</p></article>@empty<p>Nenhuma transmissão ao vivo.</p>@endforelse</section>
<section class="settings-panel"><h2>Próximas transmissões</h2>@forelse($schedule as $item)<p><strong>{{ optional($item->starts_at)->format('d/m/Y H:i') ?: 'Sem horário' }}</strong> — {{ $item->channel->name }} · {{ $item->title }}</p>@empty<p>Sem agenda futura.</p>@endforelse</section>
<section class="category-admin-list"><h2>Vídeos recentes</h2>@foreach($videos as $video)<article class="settings-panel"><strong>{{ $video->title }}</strong><p>{{ $video->is_published?'publicado':'rascunho' }} · {{ $video->provider }}</p></article>@endforeach</section>
<section class="category-admin-list"><h2>Roteiros</h2>@foreach($scripts as $script)<article class="settings-panel"><strong>{{ $script->title }}</strong><p>{{ $script->status }} · {{ $script->provider }} · {{ $script->estimated_duration_seconds }}s</p></article>@endforeach</section>
<section class="category-admin-list"><h2>Recortes</h2>@foreach($clips as $clip)<article class="settings-panel"><strong>{{ $clip->title }}</strong><p>{{ $clip->aspect_ratio }} · {{ $clip->status }}</p></article>@endforeach</section>
@endsection
