@extends('layouts.app',['title'=>'Agência Assistida - Luzicity'])
@section('content')
<section class="content-band"><p class="eyebrow">Consolidação 10.4</p><h1>Agência Assistida</h1><p>Coleta e análise automatizadas com limites, rastreabilidade e decisão editorial humana obrigatória.</p></section>
<section class="system-health-stats">@foreach($stats as $label=>$value)<article class="settings-panel system-health-stat"><span>{{ str_replace('_',' ',$label) }}</span><strong>{{ $value }}</strong></article>@endforeach</section>
<section class="settings-panel"><a class="secondary-action" href="{{ route('admin.agency-approval.index') }}">Fila de aprovação</a> <a class="secondary-action" href="{{ route('admin.rss-trends.index') }}">Tendências</a> <a class="secondary-action" href="{{ route('admin.rss-pre-pitches.index') }}">Pré-pautas</a></section>
<section class="category-admin-list"><h2>Política de fontes</h2>@foreach($feeds as $feed)<article class="settings-panel"><h3>{{ $feed->name }}</h3><p>{{ $feed->last_failure_message ?: 'Sem falha recente' }}</p><form method="post" action="{{ route('admin.agency-dashboard.policy',$feed) }}" class="admin-form">@csrf @method('put')<label>Política <select name="source_policy">@foreach(['review'=>'Revisão','trusted'=>'Confiável','blocked'=>'Bloqueada'] as $key=>$label)<option value="{{ $key }}" @selected($feed->source_policy===$key)>{{ $label }}</option>@endforeach</select></label><label>Limite por coleta <input type="number" name="max_items_per_run" min="1" max="30" value="{{ $feed->max_items_per_run }}"></label><label class="inline-check"><input type="checkbox" name="require_human_review" value="1" @checked($feed->require_human_review)> Exigir revisão humana</label><button class="secondary-action">Salvar política</button></form></article>@endforeach</section>
<section class="settings-panel"><h2>Execuções recentes</h2>@forelse($runs as $run)<p><strong>{{ $run->feed->name }}</strong> · {{ $run->status }} · {{ $run->created_count }} novas · {{ $run->duplicate_count }} duplicadas · {{ optional($run->started_at)->format('d/m H:i') }}</p>@empty<p>Sem execuções.</p>@endforelse</section>
<section class="settings-panel"><h2>Decisões auditadas</h2>@forelse($actions as $action)<p>{{ $action->user->name }} · {{ $action->action }} · {{ $action->created_at->format('d/m H:i') }}</p>@empty<p>Sem decisões.</p>@endforelse</section>
@endsection
