@extends('layouts.app')
@section('title','Memória Editorial')
@section('content')
<section class="content-band"><p class="eyebrow">Central Editorial IA</p><h1>Memória Editorial Avançada</h1><p>Identidade, vocabulário e políticas que orientam a IA sem retirar a aprovação do editor humano.</p>
@if(session('status'))<p><strong>{{ session('status') }}</strong></p>@endif
<div class="memory-grid">@foreach($profiles as $profile)<article class="admin-card"><h2>{{ $profile->name }}</h2><p>{{ $profile->is_default?'Perfil padrão':($profile->category?->name?'Categoria: '.$profile->category->name:'Perfil específico') }}</p><p>{{ $profile->rules_count }} regras · {{ $profile->terms_count }} termos</p><a class="primary-action" href="{{ route('admin.ai.memory.edit',$profile) }}">Editar memória</a></article>@endforeach</div>
<details class="admin-card"><summary><strong>Novo perfil editorial</strong></summary><form method="post" action="{{ route('admin.ai.memory.profiles.store') }}" class="memory-form">@csrf
<label>Nome<input name="name" required></label><label>Categoria<select name="category_id"><option value="">Geral</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></label><label>Idioma<input name="language" value="pt-BR" required></label><label>Tom<input name="tone" value="jornalístico profissional, claro e acessível" required></label><label>Público-alvo<input name="target_audience"></label><label>Região prioritária<input name="priority_region" value="Luziânia, Entorno do Distrito Federal e Goiás"></label><label>Título máximo<input type="number" name="max_title_length" value="70"></label><label>Resumo máximo<input type="number" name="max_excerpt_length" value="180"></label><label><input type="checkbox" name="require_source_attribution" value="1" checked> Exigir fonte</label><label><input type="checkbox" name="avoid_sensationalism" value="1" checked> Evitar sensacionalismo</label><label><input type="checkbox" name="is_default" value="1"> Perfil padrão</label><label>Diretrizes gerais<textarea name="editorial_rules" rows="5"></textarea></label><button class="primary-action">Criar perfil</button></form></details></section>
<style>.memory-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:1rem}.admin-card{padding:1rem;margin-top:1rem;border:1px solid var(--border);border-radius:18px}.memory-form{display:grid;gap:.8rem;margin-top:1rem}.memory-form label{display:grid;gap:.3rem}.memory-form input,.memory-form select,.memory-form textarea{width:100%;padding:.65rem}</style>
@endsection
