@extends('layouts.app')
@section('title',$profile->name)
@section('content')
<section class="content-band"><p class="eyebrow">Memória Editorial</p><h1>{{ $profile->name }}</h1>@if(session('status'))<p><strong>{{ session('status') }}</strong></p>@endif
<form class="admin-card form-grid" method="post" action="{{ route('admin.ai.memory.update',$profile) }}">@csrf @method('put')
<label>Nome<input name="name" value="{{ $profile->name }}" required></label><label>Categoria<select name="category_id"><option value="">Geral</option>@foreach($categories as $c)<option value="{{ $c->id }}" @selected($profile->category_id==$c->id)>{{ $c->name }}</option>@endforeach</select></label><label>Idioma<input name="language" value="{{ $profile->language }}" required></label><label>Tom<input name="tone" value="{{ $profile->tone }}" required></label><label>Público-alvo<input name="target_audience" value="{{ $profile->target_audience }}"></label><label>Região prioritária<input name="priority_region" value="{{ $profile->priority_region }}"></label><label>Título máximo<input type="number" name="max_title_length" value="{{ $profile->max_title_length }}"></label><label>Resumo máximo<input type="number" name="max_excerpt_length" value="{{ $profile->max_excerpt_length }}"></label><label><input type="checkbox" name="require_source_attribution" value="1" @checked($profile->require_source_attribution)> Exigir fonte</label><label><input type="checkbox" name="avoid_sensationalism" value="1" @checked($profile->avoid_sensationalism)> Evitar sensacionalismo</label><label><input type="checkbox" name="is_default" value="1" @checked($profile->is_default)> Perfil padrão</label><label class="wide">Diretrizes gerais<textarea name="editorial_rules" rows="7">{{ $profile->editorial_rules }}</textarea></label><button class="primary-action">Salvar perfil</button></form>
<div class="two-col"><section class="admin-card"><h2>Termos</h2><form method="post" action="{{ route('admin.ai.memory.terms.store',$profile) }}" class="stack">@csrf<input name="term" placeholder="Termo" required><input name="replacement" placeholder="Substituição"><select name="type"><option value="preferred">Preferencial</option><option value="forbidden">Proibido</option><option value="spelling">Grafia oficial</option></select><input name="context" placeholder="Contexto"><label><input type="checkbox" name="active" value="1" checked> Ativo</label><button class="secondary-action">Adicionar</button></form>
@foreach($profile->terms as $term)<form method="post" action="{{ route('admin.ai.memory.terms.update',$term) }}" class="item">@csrf @method('put')<input name="term" value="{{ $term->term }}"><input name="replacement" value="{{ $term->replacement }}"><select name="type">@foreach(['preferred','forbidden','spelling'] as $type)<option @selected($term->type===$type)>{{ $type }}</option>@endforeach</select><input name="context" value="{{ $term->context }}"><label><input type="checkbox" name="active" value="1" @checked($term->active)> ativo</label><button>Salvar</button><button formmethod="post" formaction="{{ route('admin.ai.memory.terms.destroy',$term) }}" name="_method" value="delete">Excluir</button></form>@endforeach</section>
<section class="admin-card"><h2>Regras</h2><form method="post" action="{{ route('admin.ai.memory.rules.store',$profile) }}" class="stack">@csrf<input name="name" placeholder="Nome" required><select name="rule_type">@foreach(['legal','source_attribution','anti_sensationalism','minors','victims','accusations','politics','corrections','category'] as $type)<option>{{ $type }}</option>@endforeach</select><textarea name="instruction" placeholder="Instrução" required></textarea><input type="number" name="priority" value="100"><label><input type="checkbox" name="active" value="1" checked> Ativa</label><button class="secondary-action">Adicionar</button></form>
@foreach($profile->rules as $rule)<form method="post" action="{{ route('admin.ai.memory.rules.update',$rule) }}" class="item">@csrf @method('put')<input name="name" value="{{ $rule->name }}"><select name="rule_type">@foreach(['legal','source_attribution','anti_sensationalism','minors','victims','accusations','politics','corrections','category'] as $type)<option @selected($rule->rule_type===$type)>{{ $type }}</option>@endforeach</select><textarea name="instruction">{{ $rule->instruction }}</textarea><input type="number" name="priority" value="{{ $rule->priority }}"><label><input type="checkbox" name="active" value="1" @checked($rule->active)> ativa</label><button>Salvar</button><button formmethod="post" formaction="{{ route('admin.ai.memory.rules.destroy',$rule) }}" name="_method" value="delete">Excluir</button></form>@endforeach</section></div>
<details class="admin-card"><summary><strong>Memória compilada enviada à IA</strong></summary><pre>{{ $compiled }}</pre></details></section>
<style>.admin-card{padding:1rem;margin-top:1rem;border:1px solid var(--border);border-radius:18px}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}.form-grid label,.stack{display:grid;gap:.35rem}.wide{grid-column:1/-1}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.stack input,.stack select,.stack textarea,.form-grid input,.form-grid select,.form-grid textarea{width:100%;padding:.6rem}.item{display:grid;gap:.4rem;padding:.8rem 0;border-top:1px solid var(--border)}pre{white-space:pre-wrap}@media(max-width:850px){.two-col,.form-grid{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
@endsection
