<?php
namespace App\Http\Controllers;use App\Jobs\GenerateNewsNarrationJob;use App\Models\AudioVoiceProfile;use App\Models\NewsArticle;use App\Models\NewsNarration;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Str;use Illuminate\View\View;
class AdminNewsNarrationController extends Controller{
 public function index():View{$this->editor();return view('admin.news-narrations.index',['voices'=>AudioVoiceProfile::where('is_active',true)->get(),'articles'=>NewsArticle::latest()->limit(50)->get(),'narrations'=>NewsNarration::with(['article','voiceProfile'])->latest()->paginate(30)]);}
 public function voice(Request $r):RedirectResponse{$this->admin();AudioVoiceProfile::create($r->validate(['name'=>'required|string|max:100','provider'=>'required|in:openai','voice'=>'required|string|max:50','model'=>'required|string|max:100','format'=>'required|in:mp3,opus,aac,flac,wav,pcm','cost_per_million_chars'=>'required|numeric|min:0'])+['is_active'=>true]);return back()->with('status','Voz cadastrada.');}
 public function store(Request $r):RedirectResponse{$this->editor();$d=$r->validate(['news_article_id'=>'required|exists:news_articles,id','audio_voice_profile_id'=>'required|exists:audio_voice_profiles,id']);$article=NewsArticle::findOrFail($d['news_article_id']);$profile=AudioVoiceProfile::findOrFail($d['audio_voice_profile_id']);$text=Str::limit(trim(strip_tags($article->title.'. '.$article->subtitle.'. '.$article->body)),12000,'');$count=mb_strlen($text);$n=NewsNarration::create($d+['status'=>'queued','input_text'=>$text,'character_count'=>$count,'estimated_cost'=>round($count/1000000*$profile->cost_per_million_chars,6),'requested_by'=>$r->user()->id]);GenerateNewsNarrationJob::dispatch($n->id);return back()->with('status','Narração enviada para a fila.');}
 public function review(Request $r,NewsNarration $narration):RedirectResponse{$this->admin();$status=$r->validate(['decision'=>'required|in:approved,rejected'])['decision'];abort_unless($narration->status==='pending_review',422,'Áudio ainda não está disponível para revisão.');$narration->update(['status'=>$status,'reviewed_by'=>$r->user()->id,'reviewed_at'=>now()]);return back()->with('status',$status==='approved'?'Áudio aprovado e liberado.':'Áudio rejeitado.');}
 private function editor():void{abort_unless(auth()->user()?->hasAnyRole(['Super Admin','Admin','Jornalista']),403);}private function admin():void{abort_unless(auth()->user()?->hasAnyRole(['Super Admin','Admin']),403);}
}
